{
 "title": "Dashboard podstawowy farma 2",
 "time": { "from": "2021-05-14T22:00:00.000Z", "to": "2021-06-01T21:59:59.000Z" },
 "panels": [
  {
   "title": "Predykcja produkcji",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"photovoltaic\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"moce\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"predykcja\")\r\n  |> filter(fn: (r) => r[\"id_farmy\"] == \"2\")\r\n  |> filter(fn: (r) => r[\"zrodlo\"] == \"sred\")"
    }
   ]
  },
  {
   "title": "wydajnosc dzienna ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"photovoltaic\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"moce\" and r._field == \"wydajnosc\"\r\n  )\r\n    |> filter(fn: (r) => r[\"id_farmy\"] == \"2\")\r\n  |> group(columns: [\"zrodlo\"])\r\n  |> aggregateWindow(every: 1d, fn: sum)"
    }
   ]
  },
  {
   "title": "Produkcja",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"photovoltaic\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"moce\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"produkcja\")\r\n  |> filter(fn: (r) => r[\"id_farmy\"] == \"2\")\r\n  |> filter(fn: (r) => r[\"zrodlo\"] == \"sred\")"
    }
   ]
  },
  {
   "title": "% mocy DC skonwertowanej na AC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"photovoltaic\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"moce\" and (r._field == \"moc_AC\" or r._field == \"moc_DC\")\r\n  )\r\n  |> aggregateWindow(every: 1d, fn: sum)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with _value: r.moc_AC / r.moc_DC* 100.0}))\r\n  |> drop(columns:[\"moc_AC\", \"moc_DC\"])"
    }
   ]
  },
  {
   "title": "Moc AC DC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"photovoltaic\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"moce\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"moc_AC\" or r[\"_field\"] == \"moc_DC\")\r\n  |> filter(fn: (r) => r[\"id_farmy\"] == \"2\")"
    }
   ]
  },
  {
   "title": "Wydajnosc ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"photovoltaic\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"moce\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"wydajnosc\")\r\n  |> filter(fn: (r) => r[\"id_farmy\"] == \"2\")\r\n  |> group(columns: [\"zrodlo\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperatura otoczenia",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"photovoltaic\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pogoda\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temp_otoczenia\")\r\n  |> filter(fn: (r) => r[\"id_farmy\"] == \"2\")\r\n  |> filter(fn: (r) => r[\"zrodlo\"] == \"2_pv\")"
    }
   ]
  },
  {
   "title": "Temperatura modułu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "query": "from(bucket: \"photovoltaic\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pogoda\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temp_modulu\")\r\n  |> filter(fn: (r) => r[\"id_farmy\"] == \"2\")\r\n  |> filter(fn: (r) => r[\"zrodlo\"] == \"2_pv\")"
    }
   ]
  },
  {
   "title": "Nasłonecznienie",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"photovoltaic\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pogoda\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temp_modulu\")\r\n  |> filter(fn: (r) => r[\"id_farmy\"] == \"2\")\r\n  |> filter(fn: (r) => r[\"zrodlo\"] == \"2_pv\")"
    }
   ]
  }
 ]
}